### ISSUE TITLE
Stairs interactions may lock character in "falling" animation (browser demo v1.3.4)

### ISSUE THREAD

**Issue by Conserp** [nicholas-maltbie/OpenKCC#194]
I observed this in the browser demo.

**Describe the bug**
Walking onto the stairs from the side may cause inappropriate "dropping" animation; it may transition into "falling" animation with character getting stuck.

**To Reproduce**
Walk into the stairs from the side. These stairs in the first screenshot at this angle seem reliable at reproducing at least the "dropping" phase.

**Screenshots**
![OpenKCCv134_stairs_bug](https://user-images.githubusercontent.com/132709739/236566776-95d12bfb-4fc8-46b1-b04c-e5fc70de08fa.png)

**Expected behavior**
Clearly, walking up the stairs from any direction should not trigger "dropping" animation. Something's off at that point already.

**Additional context**
I was playtesting the demo and noticed irregularities in interactions with "knee-high" stair steps (e.g. leftmost big-step straight stairs, 3rd step of the spiral stairs). Normally they are too high but sometimes the character will just step up anyway like this:

![OpenKCCv134_spiral_stairs](https://user-images.githubusercontent.com/132709739/236566885-5ad8b708-f557-4d36-b01b-654ed127c446.png)

And when I was trying out different angles/keys the 'real bug' happened (character is stuck):
![OpenKCCv134_spiral_stairs_bug](https://user-images.githubusercontent.com/132709739/236566911-64793f60-c05a-4297-bf70-88ded2952998.png)

**Comment by nicholas-maltbie** [comment]
Hello @Conserp, thanks for opening the issue for the bug and giving such a detailed description and screenshots!

The player will actually switch into the falling animation if it's either (1) above the ground, or (2) overlapping with another object. 

This issue is actually a combination of a few bugs:
1. Player overlap clipping into objects (especially at sharp edges like stairs). @squiddingme pointed out this issue in issue #195 for the box collider but it is present for all collider shapes. If you're unluck with some of the physics interactions this can even happen on flat surfaces. This will cause the player to be constantly stuck in the falling animation even if they seem to be standing on falling ground. Additionally, if you try to move the player, they may feel stuck in place when you start to move. 
2. The player quickly transitioning to the falling animation when stepping down making them look like they are bouncing. this is caused by the player normal vector not being computed properly when walking down stairs. The normal vector is being computed as the angle between the collider and the point of contact with the ground. But when walking down steps, this should instead be computed via the step the player is trying to stand on. We can calculate this by drawing a second ray down when computing the grounded angle. I included a small diagram showing what this looks like with two rows below.
    The first row has a red vector showing the desired normal, and a blue vector showing the computed normal, the second row shows the desired behavior with a red vector showing the desired normal, and a green vector showing the newly computed normal. 
    ![image](https://github.com/nicholas-maltbie/OpenKCC/assets/3240136/3c99c958-640d-47c9-b9e7-435dc228e494)
    I actually already follow this behavior for walking up steps which is why the falling animation bug doesn't happen as often while walking up steps.
3. The player stepping up the knee height step is caused by the step height of the player being set too high and the player collider being configured a bit too large. To get around this issue, I need to better tune the size of the collider and reduce the step height.
4. Some of the jittery falling animations is caused by the player transitioning to the falling state as soon as they leave the ground. Leaving a small coyote time between transitioning animations (I think I already have this, just need to configure it to be a bit longer and add some tests to ensure the KCCStateMachine doesn't transition too fast). 

## Action Items 

So, for action items to fix these, the root causes described in bug (1) are already listed in issue #195 I'll leave those action items for fixes there.

For the errors described in bug (2), I found this while working on foot IK placement and already wrote a patch for it. But it's separate from foot IK so I'll move that code feature and tests into a new branch to merge. 
1. [ ] Create smaller PR for patching ground normal detection when walking down steps

The last two bugs (3) and (4) both involve adjustments to the collider shape and configuration values, tweaking the values to ensure it look smooth and works as expected should be sufficient. 
2. [ ] Adjust values for character shape and step height to avoid climbing up tall steps
3. [ ] Increase Coyote Time for player animation to avoid jittering between falling and walking animation when moving on slopes.

Just as with the other issue, if you, @Conserp , or anyone else is interested in working on one of the action items (even if it's just writing up some tests or docs), feel free to leave a comment in the thread! I already have a patch for action item 1 and will work on making it into a separate PR soon. I'll open up a PR to investigate the other two as well.

**Comment by nicholas-maltbie** [comment]
I have addressed the first issue in PR #196. This should stop some of the jittery animations when walking down stairs. The build is currently in progress but should be on the live demo shortly - [Deployment action run](https://github.com/nicholas-maltbie/OpenKCC/actions/runs/4965855431)
> Create smaller PR for patching ground normal detection when walking down steps

**Comment by D-MAS** [comment]
![image](https://github.com/nicholas-maltbie/OpenKCC/assets/57054077/c1f26a96-df26-4d26-84f6-11bd946707cb)
got it with these stairs and was going to post it

**Comment by nicholas-maltbie** [comment]
> ![image](https://github.com/nicholas-maltbie/OpenKCC/assets/57054077/c1f26a96-df26-4d26-84f6-11bd946707cb)
> 
> got it with these stairs and was going to post it

Hi @D-MAS , I believe this is an issue with the colude overlapping with the ground. Was the player stuck in place while they were floating? I plan to patch this as part of the action items I described in issue #195 but I haven't had time to work on them yet. Basically need to make a play mode test to re-create this scenario but it comes up because distances of less than 1e-5 units  caused odd behavior due to floating point behavior and rounding in the physics engine, so difficult to re-create in a UT. But I hope to fix it as part of a patch in the next release, will probably add a skin width parameter similar to unity's character controller - [CharacterController.skinWidth](https://docs.unity3d.com/ScriptReference/CharacterController-skinWidth.html)

I'll probably open a separate issue for this soon, just haven't had much time these past few months!

**Comment by nicholas-maltbie** [comment]
Since this was being tracked in another issue, I'll link this to the new issue https://github.com/nicholas-maltbie/OpenKCC/issues/210. I will try to have these included in v1.5.0 (so probably not for a bit).
