### ISSUE TITLE
Box Collider Cast - sliding issue

### ISSUE THREAD

**Issue by squiddingme** [nicholas-maltbie/OpenKCC#195]
**Describe the bug**
OpenKCC works perfectly with a capsule collider cast, but there is also an alternative box collider cast. While this mostly works, the movement engine will occasionally slowly slide in a random direction on the floor (even with no input). I've observed some other unusual behaviours (like getting "caught" on flat ground) with box collider cast that do not occur with an equivalent capsule collider cast, though these may be down to implementation in my own project. The sliding issue, however, can be reproduced in the sample scene.

**To Reproduce**
In the sample scene for OpenKCC, unpack the character prefab and swap out the capsule collider and CapsuleColliderCast component for their respective box equivalents. Jump around a little bit on flat ground until the issue is observed.

**Comment by nicholas-maltbie** [comment]
Hello @squiddingme, thanks for opening the issue on the project, this sliding across surfaces is an issue I've had in the project for a bit, and I have been able to reproduce it locally.  I tried to patch this sometime in the past, but I guess I brought it back or didn't fix it fully. Need to write better tests. 

It's a result of the interactions between some unrelated parts of code.
I'll add a flowchart of this to the docs as well, but the movement code basically follows these steps:

1. Push out of overlapping objects
2. Move based on player input
3. Snap player down to ground if they were grounded at the start of the frame.

Any one of these steps can cause this incorrect behavior but usually pushing out of overlapping objects or moving based on player input causes these errors. This is caused because unity will sometimes detect a small collision/overlap between objects when they are very close to each other (less than 0.001 units). So, the solution I've generally found is to have the player float above the ground by at least 0.001 units.

However, this also means that the following adjustments need to be made
1. When pushing out of overlapping objects, ensure the player is slightly larger by a factor of 0.001
2. Ensure that when moving, the player will stop motion at about 0.001 units in front of whatever they collide with
3. When grounding, ensure there is at least 0.001 space between the player and the ground.

This value of 0.001 is defined as [KCCUtils.Epsilon](https://nickmaltbie.com/OpenKCC/docs/api/nickmaltbie.OpenKCC.Utils.KCCUtils.html#nickmaltbie_OpenKCC_Utils_KCCUtils_Epsilon).

## Action Items

The action items to fix this would be:
* [ ] Create an automated test to reproduce the sliding behavior in PlayMode by having the player overlap with the ground correctly (Probably test this under the [KCCMovemengEngine](https://github.com/nicholas-maltbie/OpenKCC/blob/main/Packages/com.nickmaltbie.openkcc/OpenKCC/Character/KCCMovementEngine.cs) but that does not have PlayMode tests yet).
    * [ ] After the test is made, adjust the code so this overlapping behavior does not happen and confirm via automated test.
* [ ] Add an overlap size buffer for collider size when computing overlapping shapes via [IColliderCast](https://github.com/nicholas-maltbie/OpenKCC/blob/main/Packages/com.nickmaltbie.openkcc/OpenKCC/Utils/IColliderCast.cs)
* [ ] Create individual tests and fixes for each of the root causes (pushing out overlap, player bouncing, and grounded distance) in EditMode:
    * [ ] Overlap size tests for [CapulseColliderCast](https://github.com/nicholas-maltbie/OpenKCC/blob/main/Packages/com.nickmaltbie.openkcc/OpenKCC/Utils/ColliderCast/CapsuleColliderCast.cs), [BoxColliderCast](https://github.com/nicholas-maltbie/OpenKCC/blob/main/Packages/com.nickmaltbie.openkcc/OpenKCC/Utils/ColliderCast/BoxColliderCast.cs), and [SphereColliderCast](https://github.com/nicholas-maltbie/OpenKCC/blob/main/Packages/com.nickmaltbie.openkcc/OpenKCC/Utils/ColliderCast/SphereColliderCast.cs) with a modifiable radius buffer
    * [ ] Ensure bouncing movement results in the player being at least 0.001 units away from the hit surface via [KCCUtils.SingleKCCBounce](https://github.com/nicholas-maltbie/OpenKCC/blob/65715f28c172e17caa704c84730fe60893d737e4/Packages/com.nickmaltbie.openkcc/OpenKCC/Utils/KCCUtils.cs#L335)
    * [ ] Ensure computing grounded distance results in player floating slightly off the ground by at least 0.001 units via the [KCCUtils.GetSnapDelta](https://github.com/nicholas-maltbie/OpenKCC/blob/65715f28c172e17caa704c84730fe60893d737e4/Packages/com.nickmaltbie.openkcc/OpenKCC/Utils/KCCUtils.cs#L119) function. This could even be a configurable parameter with `KCCUtils.Epslion` being the default value.

If you, @squiddingme, or anyone else is interested in working on one of the action items (even if it's just writing up some tests or docs), feel free to leave a comment in the thread! I'll probably start working on some of these action items over the weekend!

**Comment by nicholas-maltbie** [comment]
Since this was being tracked in another issue, I'll link this to the new issue #210. I will try to have these included in v1.5.0 (so probably not for a bit).
