### ISSUE TITLE
Fix jitter in wide corners 

### ISSUE THREAD

**Issue by SanielX** [nicholas-maltbie/OpenKCC#42]
It seems like if you try to walk into corner that is is wider than 90 degrees character starts to jitter a lot in place.

To solve it I checked source code for PhysX character controller and here is something I found:
```c++
// https://github.com/NVIDIAGameWorks/PhysX-3.4/blob/master/PhysX_3.4/Source/PhysXCharacterKinematic/src/CctCharacterController.cpp
// From Quake2: "if velocity is against the original velocity, stop dead to avoid tiny occilations in sloping corners"
if((currentDirection.dot(direction)) <= 0.0f)
    break;
```

Surprisingy enough, adding this to sweep test loop indeed solved the problem.
`direction` represents initial direction of the sweep and `currentDirection` is projected since last hit

**Comment by nicholas-maltbie** [comment]
Hey @SanielX, thanks for reporting the bug and a possible fix. There are still a few bugs with tight corners and narrow hallways (one funny one where if a hallway's width is the same as the player's the player will get stuck in it). I'm adding formal test scenarios and I'll add this to the integration tests in the next few days.

I was able to reproduce the error you're talking about by walking into the curved stairwell in the testing area, here is a gif sample. This is the same error you were talking about, correct?
![jittery-corner](https://user-images.githubusercontent.com/3240136/169930853-ac4e51bf-0834-4809-ab00-ac0fa6e17981.gif)

I did some work to refactor the existing KCC Movement code recently and broke it into smaller functions instead of the large monolithic function that existed before. I think the best place to address this error is the function would be the `GetProjectedMomentumSafe` method in the KCCUtils class [Link to method](https://github.com/nicholas-maltbie/OpenKCC/blob/51e2588010412b01eaade43b225ab36546b872ac/Assets/OpenKCC/Scripts/Utils/KCCUtils.cs#L243)

This character controller design is based off Quake and Nvidia's KCC so it makes sense that this would fix the errors.

Method code:
```
        public static Vector3 GetProjectedMomentumSafe(bool snappedUp, Vector3 momentum, Vector3 planeNormal, Vector3 up)
        {
            Vector3 projectedMomentum = snappedUp ? momentum : Vector3.ProjectOnPlane(
                momentum,
                planeNormal).normalized * momentum.magnitude;

            // If projected momentum is less than original momentum (so if the projection broke due to float
            // operations), then change this to just project along the vertical.
            if (projectedMomentum.magnitude + Epsilon < momentum.magnitude)
            {
                return Vector3.ProjectOnPlane(momentum, up).normalized * momentum.magnitude;
            }
            else
            {
                return projectedMomentum;
            }
        }
```

Probably checking if `projectedMomentum` and `currentDirection` are perpendicular (aka have a dot product close to zero), then we should stop the current motion (return a remaining momentum of zero). 

I'm in the process of adding some more test coverage for scenarios and full unit test coverage for the project. That way we can make sure if we fix a bug it will stay fixed in the future.

**Comment by SanielX** [comment]
Yes, I believe this staircase represents issue the same way I had it. Though to be precise, I had weirder setup which looks like this.

![image](https://user-images.githubusercontent.com/45370547/170018336-0e8f7df2-84a7-4aa4-ba1c-f4a22cdace99.png)

I guess it would make sense to compare current direction, but in my case (own KCC) this worked pretty well
```csharp
        void Move(ref Vector3 resolvedPosition, in Vector3 velocity, in GroundCheckResult groundedInfo)
        {
            int iterations = 0;

            Vector3 tempPosition = resolvedPosition;
            Vector3 remainingMove     = velocity.normalized;
            float   remainingDistance = velocity.magnitude * Time.deltaTime;
            Vector3 initialVelocityNormalized = remainingMove;
            while (remainingDistance > 0f && iterations < MaxIterationsPerFrame)
            {
                // From Quake2: "if velocity is against the original velocity, stop dead to avoid tiny occilations in sloping corners"
                // From myself: Do not care for this fact if player happens to be on slope or in air
                if (groundedInfo.IsOnStableGround && Vector3.Dot(remainingMove, initialVelocityNormalized) <= 0.0f)
                {
                    remainingDistance = 0.0f;
                    break;
                }
                /* raycast n' stuff */
             }
             /* apply motion n' stuff */
         }

```

**Comment by nicholas-maltbie** [comment]
Hey @SanielX, I was able to address this issue in PR #50. You can look over the changes in that branch, they are very similar to what you suggested, and I did have to compare it to the original momentum and not the momentum of the last bounce. 

There are a few build errors in the PR right now for the CI/CD, but the main fixes are added!
